# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 0 error(s),0 warning(s).
#brief-intro: Front-end Dev Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://0e0w.com" # the base hostname & protocol for your site

#permalink: /:year/:month/:day/:title/
permalink: /:title

# other links
#twitter_username: 0e0w
#facebook_username: 0e0w
github_username:  0e0w
email: 0e0wteam@gmail.com
#weibo_username: 0e0w
#zhihu_username: 0e0w
#linkedIn_username: 0e0w
#dribbble_username:

description_footer: 记录自己技术成长的沿途风景！

# comments
# 两种评论插件，选择其中一种即可，使用自己的 short_name
# duoshuo_shortname: hygblog
disqus_shortname: 0e0w

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
#baidu_tongji_id: cf8506e0ef223e57ff6239944e5d46a4
google_analytics_id: UA-72449510-4 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category
tag_dir: tags

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
